title: Erickneur
subtitle: Mobile Developer
description: >- # this means to ignore newlines until "baseurl:"
  Tech lover, creative, honest and I'm not afraid to let me flow. Sure, I'm also so good conceptualizing any idea with code!

url: "https://erickneur.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    #- text: Shop
    #  url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpeg
author: Erick Dávila
author_bio: "Tech lover with expertise in mobile and web development, software deployment, and database administration.

Proficient in native iOS app development using Swift, with knowledge extending to Android and cross-platform applications. Skilled in design patterns, RESTful APIs, and local storage solutions. Experienced in deploying apps to App Store Connect, Google Play Console, and App Gallery Connect.

I have worked on many types of projects, in different industries, with a robust architecture, a good user experience and the latest features, I hope the new projects are a challenge."
author_email: "erick.e.davila@gmail.com"
author_location: Everywhere 🌎
author_website_url: "https://erickneur.github.io"
typewrite-text: +++...I just being me...+++
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Vizn Performance
              company_logo: companies/viznperformance.png
              company_url: https://viznperformance.com
              designation: iOS developer
              description: "Development of iOS applications that improve the skills of professional athletes. The main tasks are creating new features using the same graphic line, improve body detection, solve bugs, repository management, deploy the projects to App Store, database design and using Microsoft tools for project management.

●	Technologies: Swift, SwiftUI, Vision, AVKit, AVFoundation, StoreKit, Laravel, MySQL, Git."
              visibility: true
            - company_name: CARI
              company_logo: companies/cari.jpeg
              company_url: https://cari.net
              designation: Sr. Software developer
              description: "Development of new features for American client applications and maintenance of existing modules. The main tasks are researching about new iOS features, review pull requests, deploy the projects to App Store and develop new modules.

●	Technologies: Swift, SwiftUI, AVKit, AVFoundation, URLSession, Azure DevOps, Git."
              visibility: true
            - company_name: Digital Geko
              company_logo: companies/digitalgeko.png
              company_url: https://digitalgeko.com
              designation: Mobile developer
              description: "Developing new features for Promerica El Salvador iOS and Android apps, assignment tasks for the team, implementing Scrum, analyses new requirements and review the deploy for App Store, Google Play and App Gallery. Also, I supported in some features of Promerica Guatemala iOS app.

●	Technologies: Objective-C, Swift, Jira, Confluence, Bitbucket, Appium, Azure, Oracle Linux, MySQL, Java, Sketch, Invision, Git."
              visibility: true
            - company_name: USAC
              company_logo: schools/usac.png
              company_url: https://usac.edu.gt
              designation: Academic Thutor
              description: "Teaching the Computational Organization laboratory as part of the 400 hours of supervised practice and contracted during the June 2018 vacation school.

●	Technologies: Java, C#, Proteus, G-suit."
              visibility: true
            - company_name: Arqco de Guatemala
              company_logo: companies/arqco.jpeg
              company_url: 
              designation: Backoffice
              description: "Working at the Plaza Tigo’s installations, developing office automation solutions for the human resources department.

●	Technologies: Visual Basic for Applications, Microsoft Office."
              visibility: true

# Education
author_education_details:
              - college_logo: schools/platzi.png
                college_name: Platzi
                college_url: https://platzi.com
                college_degree: Apple fullstack
                description: iOS mobile developer
                visibility: true
              - college_logo: schools/usac.png
                college_name: USAC
                college_url: https://postgrado.ingenieria.usac.edu.gt/proyecto-meaning/ciencias-de-la-computacion/
                college_degree: Master's degree in Computer Science
                description: With specialization in data science
                visibility: true
              - college_logo: schools/usac.png
                college_name: USAC
                college_url: https://portal.ingenieria.usac.edu.gt/redes-de-estudios/clar/ingenieria-en-ciencias-y-sistemas
                college_degree: Bachelor's degree in Computer Science
                description: Systems methodology, computer science and software development.
                visibility: true
              

# Projects
author_project_details:
              - project_thumbnail: projects/viznperformance.jpeg
                project_title: Vizn Performance apps
                project_description: iOS apps that use Vision for body poses and YOLOv8 for objects detection
                project_url: https://apps.apple.com/sa/developer/vizn-performance-inc/id1576009990
                visibility: true
              - project_thumbnail: projects/promericasv2.jpeg
                project_title: Promerica El Salvador
                project_description: Mobile banking iOS app
                project_url: https://apps.apple.com/gt/app/promerica-sv/id1597163474?platform=iphone
                visibility: true
              - project_thumbnail: projects/promericasv.webp
                project_title: Promerica El Salvador
                project_description: Mobile banking Android app
                project_url: https://play.google.com/store/apps/details?id=com.promerica.promericaES&hl=en_US&gl=US
                visibility: true
              - project_thumbnail: projects/promericagt.webp
                project_title: Promerica Guatemala
                project_description: Mobile baking iOS app
                project_url: https://apps.apple.com/gt/app/banco-promerica-guatemala/id505614199?l=en&platform=iphone
                visibility: true
              - project_thumbnail: projects/gymbars.png
                project_title: Gymbars
                project_description: Landing page for calisthenics gym
                project_url: https://gymbarsgt.com
                visibility: true

# social links
twitter_username: erickneur
github_username:  erickneur
#facebook_username: erickneur
linkedin_username: erickneur
#behance_username: erickneur
#instagram_username: erickneur
#medium_username: erickneur
telegram_username: erickneur
#dribbble_username: erickneur
#flickr_username: erickneur
stackoverflow_username: "5938089"

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
utterances: Erickneur/Erickneur.github.io
#hyvor_talk_website_id: 9150

# wakatime username (coding activity)
wakatime_username: erickneur

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us13.list-manage.com/subscribe/post?u=67f934e15436af4d4ed7f1caf&amp;id=c8a5de8f22

# contact form - (choose formspress or getform)
#getform_endpoint: 6fd7805b-137f-43d8-ad2e-4b1faaf1a0cd
formspree_endpoint: "f/myyolqaz"

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
