title: Erickneur
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://erickneur.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    #- text: Shop
    #  url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpeg
author: Erick Dávila
author_bio: Tech lover outstanding in mobile and web development, management of architectures and software deployment, administration of various databases and agile development methodologies.
author_email: "eedhcontact@gmail.com"
author_location: Guatemala
author_website_url: "https://erickneur.github.io"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Vizn Performance
              company_logo: companies/viznperformance.png
              company_url: https://viznperformance.com
              designation: iOS developer
              description: Developing iOS app in SwiftUI to analyze biomechanics in real-time using Vision to detect body poses and YOLOv3 for objects. This project is managed using Microsoft tools.
              visibility: true
            - company_name: Digital Geko
              company_logo: companies/digitalgeko.png
              company_url: https://digitalgeko.com
              designation: Mobile developer
              description: Managing multinational mobile banking for Android and iOS, implementing Scrum with Atlassian tools (Bitbucket, Jira, Confluence).
              visibility: true

# Education
author_education_details:
              - college_logo: schools/usac.png
                college_name: USAC
                college_url: https://usac.edu.gt
                college_degree: Computer Science
                description: Bachelor of Technology
                visibility: true
              - college_logo: schools/platzi.png
                college_name: Platzi
                college_url: https://platzi.com
                college_degree: Apple fullstack
                description: iOS mobile developer
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: projects/golfkinetics.png
                project_title: Golf Kinetics
                project_description: iOS app that can help anyone get better at golf 
                project_url: https://apps.apple.com/ro/app/golf-kinetics/id1636172351?platform=iphone
                visibility: true
              - project_thumbnail: projects/promericasv.webp
                project_title: Promerica El Salvador
                project_description: Mobile banking app
                project_url: https://play.google.com/store/apps/details?id=com.promerica.promericaES&hl=en_US&gl=US
                visibility: true
              - project_thumbnail: projects/promericagt.webp
                project_title: Promerica Guatemala
                project_description: Mobile baking app
                project_url: https://apps.apple.com/gt/app/banco-promerica-guatemala/id505614199?l=en&platform=iphone
                visibility: true
              - project_thumbnail: projects/gymbars.png
                project_title: Gymbars
                project_description: Landing page for calisthenics gym
                project_url: https://gymbarsgt.com
                visibility: true

# social links
twitter_username: erickneur
github_username:  erickneur
#facebook_username: erickneur
linkedin_username: erickneur
#behance_username: erickneur
#instagram_username: erickneur
#medium_username: erickneur
telegram_username: erickneur
#dribbble_username: erickneur
#flickr_username: erickneur
stackoverflow_username: "5938089"

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
utterances: Erickneur/Erickneur.github.io
#hyvor_talk_website_id: 9150

# wakatime username (coding activity)
wakatime_username: erickneur

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us13.list-manage.com/subscribe/post?u=67f934e15436af4d4ed7f1caf&amp;id=c8a5de8f22

# contact form - (choose formspress or getform)
#getform_endpoint: 6fd7805b-137f-43d8-ad2e-4b1faaf1a0cd
formspree_endpoint: "f/myyolqaz"

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
